[pytest]
markers =
    smoke: Pruebas críticas y rápidas (ej. Login exitoso)
    login: Todas las pruebas relacionadas al login
    catalogo: Pruebas de la vista de productos
    carrito: Pruebas del flujo de compras